# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setup.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Setup")
        Dialog.resize(400, 205)
        Dialog.setSizeGripEnabled(True)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(50, 170, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 381, 141))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.selectSteam = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.selectSteam.setObjectName("selectSteam")
        self.gridLayout.addWidget(self.selectSteam, 0, 1, 1, 1)
        self.playerName = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.playerName.setAutoFillBackground(False)
        self.playerName.setStyleSheet("margin:10")
        self.playerName.setObjectName("playerName")
        self.gridLayout.addWidget(self.playerName, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.selectObs = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.selectObs.setObjectName("selectObs")
        self.gridLayout.addWidget(self.selectObs, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.selectDemo = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.selectDemo.setObjectName("selectDemo")
        self.gridLayout.addWidget(self.selectDemo, 2, 1, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Setup"))
        self.selectSteam.setText(_translate("Dialog", "Select Folder"))
        self.label_6.setAccessibleName(_translate("Dialog", "Steam Location"))
        self.label_6.setText(_translate("Dialog", "Enter Player username"))
        self.label.setAccessibleName(_translate("Dialog", "Steam Location"))
        self.label.setText(_translate("Dialog", "Select Steam Folder"))
        self.label_7.setAccessibleName(_translate("Dialog", "Steam Location"))
        self.label_7.setText(_translate("Dialog", "Select OBS Studio Exe"))
        self.selectObs.setText(_translate("Dialog", "Select File"))
        self.label_5.setAccessibleName(_translate("Dialog", "Steam Location"))
        self.label_5.setText(_translate("Dialog", "Select Demo"))
        self.selectDemo.setText(_translate("Dialog", "Select File"))
